### ISSUE TITLE
Update 'README.md' cloudformation interpolation examples

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/opensearch_customization#48]
We need to update our CloudFormation interpolation syntax as follows:

```yaml
    OpenSearchDeleteDocumentRule:
        Type: AWS::Events::Rule
        Properties:
            Name: !Sub ${FunctionNameOpenSearchConfiguration}DeleteIndexDocuments
            Description: !Sub |
                trigger ${FunctionNameOpenSearchConfiguration} to delete index
                documents older than or equal to 30 days from now
            ScheduleExpression: cron(0 4 * * ? *)
            State: !Ref EnableEventRules
            Targets:
              - Id: OpenSearchDeleteDocumentRule
                Arn: !GetAtt OpenSearchConfigurationFunction.Arn
                Input: !Sub
                  - '{
                        "RequestType": "Create",
                        "ResourceProperties": {
                            "OpenSearchDomain": "https://${OpenSearchDomain}",
                            "OpenSearchIndex": "${OpenSearchIndex}",
                            "DocumentDeleteRange": {
                                "message.utc": { "lte": "now-30d" }
                            }
                        }
                    }'
                  - OpenSearchDomain: !Sub OpenSearch.Outputs.NestedOpenSearchDomainEndpoint
                    OpenSearchIndex: !Ref OpenSearchIndex

                RetryPolicy:
                    MaximumEventAgeInSeconds: !Ref MaximumEventAgeInSeconds
                    MaximumRetryAttempts: !Ref MaximumRetryAttempts
        DependsOn: [OpenSearchConfigurationFunction, OpenSearchConfiguration]
```

Otherwise, each line of the json string will be received by python/lambda containing a newline character.
